# Generated by Django 3.0.5 on 2020-04-23 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('tipocategoria', models.CharField(max_length=15, verbose_name='Tipo da Categoria')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('datamovimentacao', models.DateTimeField(verbose_name='Data da movimentaçcão')),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacao.Categoria')),
                ('usuario_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimentação',
                'verbose_name_plural': 'movimentações',
                'db_table': 'movimentacao',
            },
        ),
    ]
